# Generated by Django 5.2.4 on 2025-07-24 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Main headline", max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Secondary text", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Brief description"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Recommended: 1920x800px", upload_to="slider/"
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Mobile optimized image (optional)",
                        null=True,
                        upload_to="slider/mobile/",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, help_text="Button text", max_length=50
                    ),
                ),
                ("cta_link", models.URLField(blank=True, help_text="Button link")),
                (
                    "cta_internal_page",
                    models.CharField(
                        blank=True,
                        help_text="Internal page name (e.g., 'products', 'contact')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="inverter",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="inverter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
