# Generated by Django 5.2.4 on 2025-07-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageslider",
            name="mobile_image",
        ),
    ]
